---
title: "DESeq2 quick report:"
output: html_document
---

%\VignetteEngine{knitr::knitr}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
pcutoff <- 0.01
basedir = './results'
files <-c('out.tsv')

library(data.table)
library(tidyverse)
```

```{r}
for (tablein in files) {
  message( tablein )

  dt <- fread(file.path(basedir, tablein))
  
  # Effect sizes
  message('Effect sizes')
  print(
    ggplot(dt, aes(x=log2FoldChange)) +
      geom_histogram(bins = 100) +
      scale_y_sqrt() +
      ggtitle(tablein)
  )
  
  # Volcano
  print( 
    ggplot(dt, aes(x=log2FoldChange, y=-log10(padj))) +
      geom_point(shape=16, alpha=0.3, size=rel(0.5)) +
      ggtitle(tablein)
  )
  
  # Top 100 p
  message('Top 100 padj')
  print(
    dt[complete.cases(dt), ] %>%
      arrange(padj, abs(log2FoldChange), lfcSE) %>%
      select(-pvalue) %>%
      head(n=100)
  )
  
  # Top 100 fc-
  message(paste('Top 100 down-regulated, padj <', pcutoff))
  print(
    dt[complete.cases(dt), ] %>%
      filter(padj < 0.01) %>%
      arrange(log2FoldChange, padj, lfcSE) %>%
      select(-pvalue) %>%
      head(n=100)
  )
  
  # Top 100 fc+
  print(paste('Top 100 up-regulated, padj <', pcutoff))
  print(
    dt[complete.cases(dt), ] %>%
      filter(padj < 0.01) %>%
      arrange(desc(log2FoldChange), padj, lfcSE) %>%
      select(-pvalue) %>%
      head(n=100)
  )
}
```
