---
title: "PCA"
author: "Kimon Froussios"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    code_folding: hide
    toc: yes
---

\VignetteEngine{knitr::knitr}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r message=FALSE, warning=FALSE}
library(data.table)
library(matrixStats)
library(ggplot2)
library(ggExtra)
library(plotly)
library(htmltools)

theme_set(theme_bw())
minL = 0.75
maxN = 50

# Calculate PCA and plots
do_pca <- function(counts, covars, center=TRUE, scale=TRUE, loadthresh = 0.75){
  # Convert table to matrix
  countsmat <- as.matrix(counts[, 2:length(counts)])
  rownames(countsmat) <- counts$Geneid
  
  # Gene variances
  genevar <- data.table(name = rownames(countsmat),
                        Mean = rowMeans(countsmat),
                        StDev = rowVars(countsmat) )
  
  # Rotate counts so genes are variables and samples are observations
  countsmat <- t(countsmat)
  
  # Add covariates info
  counts <- cbind(covars, as.data.table(countsmat))
  rownames(counts) <- rownames(countsmat)

  # Calculate principal components (after getting rid of zero-variance genes that can't be standardized).
  
  nonconstant <- which(apply(countsmat, 2, var)!=0)
  countsmat <- countsmat[, nonconstant]
  nvars <- dim(countsmat)[2]
  
  pca <- prcomp(countsmat, center = center, scale. = scale)
  srn <- sqrt(nrow(countsmat) - 1)
  pc <- sweep(pca$x, 2, 1 / (pca$sdev * srn), FUN = '*')
  pc <- cbind(pc, data.frame(name = rownames(pc)))
  pc <- merge(pc, covars, by.x = "name", by.y="sample", all = TRUE)
  npc <- sum(pca$sdev > 1)
    
  # Screeplot.
  
  pcaimp <- as.data.table(cbind(as.data.frame(t(summary(pca)$importance)), 
                  data.frame(PC = 1:length(colnames(pca$x)))))
  pcaimp <- melt(pcaimp, variable.name = "type", value.name = "Proportion", id.vars = c("PC", "Standard deviation"))
  
  pcmax=15
  pimp <- ggplot(pcaimp[(PC<pcmax),], aes(x=PC, y=Proportion)) +
    facet_grid(type ~ ., scales="free_y") +
    geom_bar(aes(fill=type), stat="identity", width=0.6) +
    geom_line(aes(colour=type)) +
    scale_fill_manual(values = c("grey50", "transparent")) +
    scale_colour_manual(values = c("transparent", "grey25")) +
    scale_x_continuous(breaks = seq(1, pcmax, 2)) +
    labs(title = "PCA Screeplot", subtitle=paste0(nvars, " features, ", npc, " PCs"), x = "Principal Component") +
    theme(axis.title.y = element_blank(),
          legend.position = "none")

  # Top loadings for the first 3 PCs.
  
  loads <- as.data.table(t(t(pca$rotation) * pca$sdev))
  loads[, rowID := rownames(pca$rotation)]
  loads <- melt(loads, value.name = "Loading", id.vars="rowID", variable.name="PC")
  loads[, absload := abs(Loading)]
  lhigh <- loads$absload > loadthresh     # keep only high loadings
  setorder(loads, PC, -absload)
  sel1 <- loads[lhigh > loadthresh & PC=="PC1", rowID]
  sel2 <- loads[lhigh > loadthresh & PC=="PC2", rowID]
  sel3 <- loads[lhigh > loadthresh & PC=="PC3", rowID]
  sel <- unique(loads[lhigh, rowID])
  
  # Coefficient names.
  
  ig <- names(covars)
  ig <- ig[! ig %in% c('sample', 'Sample', 'name', 'Name', 'sizeFactor')]

  # Means and Variances of the top loads in the first 3 PCs.
  
  genevar = data.table(rowID = colnames(countsmat),
                       Mean = colMeans(countsmat), 
                       StDev = colSds(countsmat) )
  genevar[, istop:= rowID %in% sel]
  
  pvar1 <- ggMarginal(ggplot(genevar) +
      geom_point(aes(x=Mean, y=StDev, label=rowID, colour=istop), shape=16, size=0.8, alpha=0.5) +
      scale_x_log10() +
      scale_colour_manual(values=c("black", "violetred")) +
      scale_y_log10() +
      labs(x="Mean", y="Standard Deviation", title="All features") +
      theme(legend.position = "none"),
    type = "histogram")
  
  pvar2 <- ggplot(genevar[(istop),]) +
      geom_point(aes(x=Mean, y=StDev, label=rowid), shape=16, size=0.8, alpha=0.5, colour="purple") +
      labs(x="Mean", y="Standard Deviation", 
           title="Top-loading features", subtitle = "in the first 3 PCs") +
      scale_x_log10() +
      scale_y_log10()
  
  # Correlation of the samples for the selected features only.
  
  genec <- cor(t(countsmat[, sel]))
  hcfit <- hclust(dist(t(genec)))
  rn <- rownames(genec)
  genec <- as.data.table(genec)
  genec[, observation1 := rn]
  genec <- melt(genec, id.vars = "observation1", value.name = "correlation", variable.name = "observation2")
  genec[, observation1 := factor(observation1, ordered=TRUE, 
                                 levels=rn[hcfit$order]) ]
  genec[, observation2 := factor(observation2, ordered=TRUE, 
                                 levels=rn[hcfit$order]) ]
  
  pcor1 <- ggplot(genec, aes(x=observation1, y=observation2, fill=correlation, label=correlation)) +
    geom_tile() +
    # geom_text(colour="white") +
    # scale_x_discrete(position="top") +
    scale_fill_gradientn(limits=c(-1, 1), colors=c("steelblue2", "blue", "darkblue", "black", "darkred", "red", "orange", "yellow") ) +
    labs(x='', y='', title="Correlation of samples", subtitle="(top loading in first 3PCs)") +
    theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
  
  # # Correlation of the selected features.
  # 
  # genec <- cor(countsmat[, sel])
  # hcfit <- hclust(dist(t(genec)))
  # rn <- rownames(genec)
  # genec <- as.data.table(genec)
  # genec[, observation1 := rn]
  # genec <- melt(genec, id.vars = "observation1", value.name = "correlation", variable.name = "observation2")
  # genec[, observation1 := factor(observation1, ordered=TRUE, 
  #                                levels=rn[hcfit$order]) ]
  # genec[, observation2 := factor(observation2, ordered=TRUE, 
  #                                levels=rn[hcfit$order]) ]
  # 
  # pcor2 <- ggplot(genec, aes(x=observation1, y=observation2, fill=correlation, label=correlation)) +
  #   geom_tile() +
  #   # geom_text(colour="white") +
  #   # scale_x_discrete(position="top") +
  #   scale_fill_gradientn(limits=c(-1, 1), colors=c("steelblue2", "blue", "darkblue", "black", "darkred", "red", "orange") ) +
  #   labs(x='', y='', title="Correlation of top-loading features", subtitle="(in first 3 PCs)") +
  #   theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
  # if (sqrt(dim(genec)[1]) >50) {
  #   pcor2 <- pcor2 + theme(axis.text.x = element_blank(), 
  #                          axis.text.y = element_blank(),
  #                          axis.ticks = element_blank() )
  # }

  # Plot first 3 PCs in 2D pairs.
  # Highlight one variable at a time.
  pc12 <- lapply(ig, function(varname) { 
    return( 
      ggplot(pc, aes_string(x="PC1", y="PC2", label="name", colour=varname)) +
        geom_point(shape=16) +
        coord_fixed()
    )})
  # do.call(grid.arrange, c(l1, ncol=2))

  pc13 <- lapply(ig, function(varname) { 
    return( 
      ggplot(pc, aes_string(x="PC1", y="PC3", label="name", colour=varname)) +
        geom_point(shape=16) +
        coord_fixed()
    )})
  # do.call(grid.arrange, c(l2, ncol=2))

  pc23 <- lapply(ig, function(varname) { 
    return( 
      ggplot(pc, aes_string(x="PC2", y="PC3", label="name", colour=varname)) +
        geom_point(shape=16) +
        coord_fixed()
    )})
  # do.call(grid.arrange, c(l3, ncol=2))
  
  return(list(pca=pca, 
              nvars=nvars, 
              nPC=npc, 
              pimp=pimp, 
              load1=sel1, load2=sel2, load3=sel3,
              pc_1_2=pc12, pc_1_3=pc13, pc_2_3=pc23,
              pvar1=pvar1, pvar2=pvar2, 
              pcor1=pcor1 #, pcor2=pcor2
              ))
}
```

# Input

```{r input}
covars <- fread('/Volumes/groups/zuber/zubarchive/USERS/Kimon/markus/M9179_quantseq/description/covars.txt')
# Gene and sg are mutually redundant info
covars <- covars[, names(covars) != "sg", with=FALSE]
setkey(covars, sample)

xref <- fread("/Volumes/groups/zuber/zubarchive/USERS/Kimon/markus/M9179_quantseq/aux/xref_mm_genes.txt")
setkey(xref, ensembl_gene_id)

counts <- fread('/Volumes/groups/zuber/zubarchive/USERS/Kimon/markus/M9179_quantseq/process/counts/counts_rpm_named.tsv')
# g <- data.table(eid = counts$Geneid,
#                 name = xref[counts$Geneid, external_gene_name] )
# g[is.na(name), name := eid]
# counts[, Geneid := g$name]
setkey(counts, Geneid)

# fwrite(counts, file='/Volumes/groups/zuber/zubarchive/USERS/Kimon/markus/M9179_quantseq/process/counts/all_counts_renamed.tsv', sep="\t")
```

# PCA

```{r}
res <- do_pca(counts, covars, loadthresh = minL)
```

```{r}
# Scree
print(res[["pimp"]])
```

### PC1 + PC2

```{r}
htmltools::tagList(lapply(res[["pc_1_2"]], function(x) { ggplotly(x) }))
```

### PC1 + PC3

```{r}
htmltools::tagList(lapply(res[["pc_1_3"]], function(x) { ggplotly(x) }))
```

### PC2 + PC3

```{r}
htmltools::tagList(lapply(res[["pc_2_3"]], function(x) { ggplotly(x) }))
```

## Top high-loading features in the first 3 PCs

Only the `r maxN` highest-loading features with loading >= `r minL` are listed here, in order of decreasing loading. 

### PC1

```{r}
xref[head(res[["load1"]], n=maxN),]
```

### PC2

```{r}
xref[head(res[["load2"]], n=maxN),]
```

### PC3

```{r}
xref[head(res[["load3"]], n=maxN),]
```

## Correlations

Calculated using only the features with loading >= `r minL` in any of the first 3 PCs.

<!-- ### among samples -->

```{r fig.width=15, fig.height=15}
print(res[["pcor1"]])
```

<!-- ### among high-loading features -->

<!-- ```{r fig.width=10, fig.height=10} -->
<!-- print(res[["pcor2"]]) -->
<!-- ``` -->

# Session Info

```{r}
sessionInfo()
```
